import json
import os
from langchain_core.prompts import ChatPromptTemplate
# from langchain_ollama.llms import OllamaLLM
# from docx import Document
# import pdfplumber
# import pytesseract
from PIL import Image
import google.generativeai as genai
from flask import Flask, render_template, request, jsonify
from werkzeug.utils import secure_filename
import logging
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("GEMINI_API")
genai.configure(api_key='' + api_key)

class GemBot():

    model = genai.GenerativeModel("gemini-1.5-flash")
    
    def __init__(self):
        self.conversation = []

    def system(self, text):
        self.conversation = []
        self.conversation.append({'role': 'system', 'content': text})

    def sys_up(self):
        self.conversation.append(("human", "{user_input}"))

    def doc(self, path):
        try:
            ext = os.path.splitext(path)[1].lower()
            if ext == '.txt':
                with open(path, 'r') as f:
                    text = f.read()
            elif ext == '.json':
                with open(path, 'r') as f:
                    data = json.load(f)
                    text = json.dumps(data, indent=4)
            elif ext == '.docx':
                doc = Document(path)
                text = '\n'.join([para.text for para in doc.paragraphs])
            elif ext == '.pdf':
                doc = pdfplumber.open(path)
                text = ""
                for page in doc.pages:
                    text += page.extract_text()
            elif ext in ['.jpg', '.png', '.jpeg']:
                extracted_text = self.extract_text_from_image(path)
                print("Extracted Text:", extracted_text)
            else:
                print(f"Error: Unsupported file type '{ext}'")
                return
            self.conversation.append({'role': "system", 'content': f"This is the PCF statement that you need to review:\n{text}"})
            # self.sys_up()
        except FileNotFoundError:
            print(f"Error: The file '{path}' was not found.")
        except Exception as e:
            print(f"Error: {e}")

    def extract_text_from_image(self, image_path):
        # Open the image using PIL
        img = Image.open(image_path)
        text = pytesseract.image_to_string(img)
        print(text, '\n\n')
        self.conversation.append(("human", f"Here is the extracted text:\n{text}"))
        self.sys_up()
    
    def gen_out(self, text):
        self.conversation.append({'role': 'user', 'content': text})
        conv = self.build_conversation()
        response = self.model.generate_content(conv)
        output = response.text  # Adjust this based on Gemini's response structure
        # print(output, '\n')
        self.conversation.append({'role': 'assistant', 'content': output})
        # self.sys_up()
        return output

    def build_conversation(self):
        return "\n\n".join(f"{msg['role'].capitalize()}: {msg['content']}" for msg in self.conversation)


    def get_conv(self):
        for dialogue in self.conversation:
            print(dialogue)

    def load_schema(self, path):
        try:
            with open(path, 'r') as f:
                schema = f.read()
            
            self.conversation.append(("system", "You will now receive the database schema that you need to strictly follow."))
            self.conversation.append(("human", f"Here is the database schema:\n{schema}"))
            
            self.conversation.append(("human", "Based on the schema provided, please ensure to structure your outputs (like JSON) accordingly when I provide the PCF statements."))
            
            self.sys_up()
        except FileNotFoundError:
            print(f"Error: The schema file '{path}' was not found.")
        except Exception as e:
            print(f"Error: {e}")

cb1 = GemBot()

sys_text = '''
You are an AI assistant that will read through given datasets and suggest the user with any business rules that might apply the dataset. for eg:
"Valid Age": lambda row: 0 <= pd.to_numeric(row["Age"], errors="coerce") <= 120 if "Age" in row else True,
"Salary Non-negative": lambda row: pd.to_numeric(row["Salary"], errors="coerce") >= 0 if "Salary" in row else True,

You only need to output these rules in given format, do not provide any extra code or helper functions, just the rules.
Aside from these suggested rules, you may also receive a set of formatted rules generated by the user in which case you will return those in the same format:
Arbitray Rule Name/ Rule Number: lambda row:...
'''

sys_text = '''
You are an AI assistant that will read through given datasets and suggest the user with any expectations that might apply to the dataset within the list given to you.
ge_expectations = {
    1: "expect_column_to_exist",
    2: "expect_column_values_to_not_be_null",
    3: "expect_column_values_to_be_null",
    4: "expect_column_values_to_be_unique",
    5: "expect_table_row_count_to_be_between",
    6: "expect_table_column_count_to_be_between",
    7: "expect_column_values_to_be_in_set",
    8: "expect_column_values_to_not_be_in_set",
    9: "expect_column_values_to_be_of_type",
    10: "expect_column_values_to_match_regex",
    11: "expect_column_values_to_not_match_regex",
    12: "expect_column_values_to_match_strftime_format",
    13: "expect_column_values_to_be_between",
    14: "expect_column_mean_to_be_between",
    15: "expect_column_median_to_be_between",
    16: "expect_column_min_to_be_between",
    17: "expect_column_max_to_be_between",
    18: "expect_column_quantile_values_to_be_between",
    19: "expect_column_proportion_of_unique_values_to_be_between",
    20: "expect_column_value_lengths_to_be_between",
    21: "expect_column_value_lengths_to_equal",
    22: "expect_column_pair_values_to_be_equal",
    23: "expect_column_pair_values_a_to_be_greater_than_b",
    24: "expect_compound_columns_to_be_unique",
    25: "expect_select_column_values_to_be_unique_within_record",
    26: "expect_multicolumn_sum_to_equal",
    27: "expect_column_distinct_values_to_be_in_set",
    28: "expect_column_kl_divergence_to_be_less_than",
    29: "expect_column_to_exist_in_list",
    30: "expect_column_values_to_be_json_parseable"
}

example output:
{
    {
        "column": "boolean",
        "dataType": "number",
        "rules": [
            {
                "rule_id": 13,
                "value": "19,20"
            }
        ]
    },
    {
        "column": "Age",
        "dataType": "number",
        "rules": [
            {
                "rule_id": 16,
                "value": "87"
            }
        ]
    }
}

Note: Try to output as many rules as possible
you only need to output as shown in the example, do not provide any extra code or helper functions.
'''

cb1.system(sys_text)

# with open("synthetic_dirty_data.csv", "r", encoding="utf-8") as f:
#     x = f.read()

# print(cb1.gen_out(f"{x}. Read this file and generate appropriate business rules."))